version: "3.3"

networks:
  crb:

services:
  bot:
    image: ghcr.io/nathan13888/coderunnerbot/crb:latest
    container_name: crb_bot
    restart: always
    environment:
      - PISTON_URL=http://piston:2000/api/v2/
      - DOTENV=/app/.env
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - crb
    depends_on:
      - piston

  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    restart: always
    ports:
      - 2000:2000
    volumes:
      - ./data/piston:/piston
    networks:
      - crb
    tmpfs:
      - /piston/jobs:exec
      - /tmp:exec

