version: "3.3"

networks:
  crb:

services:
  bot:
    image: ghcr.io/nathan13888/coderunnerbot/crb:latest
    container_name: crb_bot
    restart: always
    environment:
      - PISTON_URL=http://piston:2000/api/v2/
      - DOTENV=/app/.env
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - crb
    depends_on:
      - piston

  piston:
    image: ghcr.io/nathan13888/coderunnerbot/piston:latest
    container_name: piston_api
    restart: always
    ports:
      - 2000:2000
    volumes:
      - ./data/piston:/piston
    #environment:
    #    - PISTON_REPO_URL=http://repo:8000/index
    networks:
      - crb
    tmpfs:
      - /piston/jobs:exec
      - /tmp:exec

#  piston-repo:
#    image: ghcr.io/nathan13888/coderunnerbot/piston-repo:latest
#    container_name: piston_repo
#    restart: always
#    command: ['--no-build']
#    volumes:
#      - ./piston:/piston
#    networks:
#      - crb

